# ML-Fundamentals - Python Numpy Basics

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
* [Exercises](#Exercises)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses)

## Introduction

In this exercise you will learn numpy operations / features, which you will need throughout nearly all data science tasks, when working with python.

## Requirements
### Knowledge

You should have a basic knowledge of:
- numpy

Suitable sources for acquiring this knowledge are:
- [numpy quickstart](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)
- [numpy slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

### Python Modules

By [deep.TEACHING](https://www.deep-teaching.org/) convention, all python modules needed to run the notebook are loaded centrally at the beginning. 


In [1]:
# External Modules
import numpy as np

## Exercises

**Task:**

Generate a numpy-1D array of length 10, all elements being 0, except the 5th element which is 1

In [29]:
### Your Solution
a = np.zeros(10)
a[4] = 1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Task:**

Reverse the order of vector `z`: The first element becomes the last, the second becomes the second last etc.

In [19]:
### Your Solution
z = np.arange(50)
z[: : -1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Task:**

Find the indices of all elements that are nonzero.

In [34]:
### Your Solution
z = np.array([1,2,0,0,4,0])
np.where(z == 0)

(array([2, 3, 5]),)

**Task:**

Generate a 10x10 array with random values and find the smallest and largest value.

In [61]:
### Your Solution
a = np.random.randint(1000, size=(10, 10))
print(a, '\n Minimum: ', np.min(a),'Maximum: ', np.max(a))


[[429 142 242 503 149 923 931 851 298 230]
 [198 628 714 776 769 150 700 552 367 841]
 [560  27 121 310 297 469 704 515 630 971]
 [118 465 639 773 773  40 705 208 338 481]
 [670 278 384 438 980 635 929 911 662 609]
 [823 602 123 986 400 864 535 378 460 662]
 [583  69 527  10  61 818 712 969 874 335]
 [858 938 938 774 971 471 886 314 817 290]
 [341 652 535 140 393 396 565 908  18 279]
 [172 248  37 827 128 584 721 626  55 768]] 
 Minimum:  10 Maximum:  986


**Task:**

Generate a vector of length 50 with random values and calculate the mean.

In [60]:
### Your Solution
v = np.random.randint(1000, size=(50))
mean = np.mean(v)
print(v, '\n Mean: ', mean)


[203 675 203 674 802 638 452 186 252 729 161 113 582  25 422 381 682 603
 485 617 660 684 345 355  22 679 381 258 863 738 167 529 732 867 299 651
 106  59 561 692 633 320 592 902 596 846 151 482  31 745] 
 Mean:  476.62


**Task:**

Explain the following results:

In [7]:
print(0 * np.nan) # calculations using NaN always return NaN
print(np.nan == np.nan) # NaN can not be compared to NaN
print(np.inf > np.nan) # You should not compare against NaN because it's not part of indinity
print(np.nan - np.nan) # again, calculation involving NaN return NaN
print(0.3 == 3 * 0.1) # Has something to do with the floating point on a bit level

nan
False
False
nan
False


**Task:**

Generate an 8x8 matrix and fill it with a chess pattern like:

`
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])
`

In [155]:
### Your Solution - took long enough
chess = np.ones(64).reshape((8,8))
for (i,j),val in np.ndenumerate(chess):
    if(i % 2 != 0):
        if(j % 2 == 0):
            chess[i][j] = 0
    else:
        if(j % 2 != 0):
            chess[i][j] = 0
print(chess)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**Task:**

Generate a random 5x5 matrix and normalize (scale) it. That means, the smallest value should become 0.0, the largest 1.0

In [163]:
### Your Solution
a = np.random.randint(100, size=(5, 5))
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))  # (a - a_min)/(a_max - a_min)
print(normalized)

[[0.09677419 1.         0.74193548 0.50537634 0.31182796]
 [0.46236559 0.43010753 0.46236559 0.62365591 0.69892473]
 [0.94623656 0.68817204 0.41935484 0.15053763 0.60215054]
 [0.58064516 0.68817204 0.48387097 0.33333333 0.        ]
 [0.39784946 0.58064516 0.75268817 0.8172043  0.21505376]]


**Task:**

From each row, subtract the maximum value of that row.

In [176]:
### Your Solution
z = np.arange(12).reshape((3,4))
print(z)
for (i,j),val in np.ndenumerate(z):
    z[i][j] = val - z[i].max()
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-3 -2 -1  0]
 [-3 -2 -1  0]
 [-3 -2 -1  0]]


**Task:**
    
Divide each column by the sum of that column. Then verify that each column adds up to 1.

In [214]:
### Your Solution
z = np.arange(12).reshape((3,4)).transpose()
print(z)
for (i,j),val in np.ndenumerate(z):
       print(val / z[i].sum())
print()

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
0.0
0.3333333333333333
0.6666666666666666
0.06666666666666667
0.3333333333333333
0.6
0.1111111111111111
0.3333333333333333
0.5555555555555556
0.14285714285714285
0.3333333333333333
0.5238095238095238



**Task:**

Negate all elements between 3 and 8 in place.

In [12]:
### Your Solution
Z = np.arange(11)


**Task:**

Explain the result (output) of the following code:

In [13]:
### Your Solution
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), axis=-1)) # axis -1
del sum

9
10


**Task:**

Generate a random vector of length 100 and sort it.

In [14]:
### Your Solution


**Task:**

Check if two arrays are equal:

    1. All elements should be exactly the same
    2. Equality within a tolerance

In [15]:
### Your Solution
A = np.random.random((3,4))
B = A.copy()
B[1,2] = A[1,2] * 1.00000000000001
print (A)

[[0.49207219 0.13076783 0.93873214 0.5086066 ]
 [0.63897564 0.80675054 0.63607369 0.00563305]
 [0.1198563  0.23738252 0.78412784 0.0705644 ]]


**Task:**

Generate (as little code as possible) the following matrix with `np.array` and save it as the variable `arr`.

\begin{bmatrix}
1 & 1 & 1 &1  &1 \\ 
1 & 2 & 1 & 1 & 1\\ 
1 & 1 & 3 & 1 & 1\\ 
1 &1  & 1 & 4 & 1
\end{bmatrix}

And calculate:
- the sum of each line
- the sum of each row

In [16]:
### Your Solution


**Task:**

Generate a 2x2 matrix from `arr`: It shall consist of the 4 values when taking the values of the 2nd and 4th column of arr and the even rows.

Use different methods:
(see http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
- integer array indexes
- slices
- boolean arrays


In [17]:
### Your Solution


**Task:**

(see http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

Explain the following operations on `arr`

In [18]:
### Your Solution
print(arr)
print('--------1-------')
print(arr * 5.)
print('--------2-------')
print(np.arange(arr.shape[1]))
print(arr * np.arange(arr.shape[1]))
print('--------3------')
print(arr.T * np.arange(arr.shape[0]))
print('--------4-------')
print(arr * np.arange(arr.shape[0]))

NameError: name 'arr' is not defined

**Task:**

Calculate the matrix-vector product (dot product) of `arr` and $v$:

with:

$
v = (1,2,3,4,5)^T
$

In [ ]:
### Your Solution


## Summary and Outlook

In this notebook you've picked up many of the essential numpy operations for maths and data science tasks.

The more you use the library, the more of its functionality you'll discover and its usage will grow more intuitive and familiar.

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Python Numpy Basics <br/>
by Klaus Strohmenger <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2019 Klaus Strohmenger

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.